// 1. Goto the mongoDb website 
// 2. Create an account (try free)
// 3. Create a project (make myself a project owner)
// 4. Then create a db cluster choose M0(free version)
// 5. Create deployment
// 6. Create usrename, (make sure I write the password down for latter use)
// 7. Then choose connection method (use mongoDbDriver(which is node.js))
// 8. Choose the first option
// 9. open terminal and run npm install mongodb
// 10. Mongoose ram(which is mongodb ram which allows us to run mongodb)
// 11. DataSetup, given a connection string( make sure to replace the given password with the password I have created)
// 12. .env dev local DB_URI = con string
// 13. create a new folder which is called database, within it create a mongodb file from mongoose
// 
// 
// 
//


// here Lemme try from W3school 
// 



